### ISSUE TITLE
Score is updated too frequently

### ISSUE THREAD

**Issue by c-to-the-fazzy** [c-to-the-fazzy/cardiathena#73]
# Problem

Currently, the hearts adjudicator appears to update the players' point totals incrementally after every trick.  However, according to the rules, points are only accrued at the end of each _round_.  

# Fix
Update the adjudicator `step_game` to only update the score when the final trick is over.

**Comment by aphelps4** [comment]
After looking into this a bit further, there is no reference to the points variable in state.py (which is something I need to clean up). I made a getter for the points a while ago in the adjudicator which gets called towards the end for updating score and also gets called while printing the trick results for testing purposes. Should I move the getter into the agents that use it or should I keep it in adjudicator since it basically ended up getting used as a score getter there?
