### ISSUE TITLE
Random Agent has no cards to play

### ISSUE THREAD

**Issue by aphelps4** [c-to-the-fazzy/cardiathena#85]
**Describe the bug**
It seems like rarely, something causes the Random Agent to run out of cards to play. I have not determined if this is because they actually have no cards or if it is because they are receiving an encoded state that determines all their cards are cards they can not play.

**To Reproduce**
Keep running play_hearts.py until you get "lucky" enough to see the error. I have attached the error message I got to give an idea of what is happening.

**Expected behavior**
The agent should always have at least one card that it can play.

**Screenshots**
![errorImg](https://user-images.githubusercontent.com/57017112/76565641-64079a00-6481-11ea-877e-ba0ce9d89281.PNG)

**Comment by c-to-the-fazzy** [comment]
@aphelps4 In order to assist in reproducibility, you can [set the numpy random seed](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html) in the beginning of `play_hearts`.   Then if you are running the games in a loop, you'll know which game it crashes on and can set a debug point before then.

**Comment by aphelps4** [comment]
Update: Low-layer passes in 0 as one of its chosen cards when passing, even if it does not have it. I assume this is an error happening where we start with a list of all 0s and the final 0 does not get set to a card the agent actually owns.

**Comment by aphelps4** [comment]
Fix is now on my Shooter Agent branch and will be merged into master once a basic shooter is completed.
